from PyQt5 import QtCore, QtGui, QtWidgets
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
from csv import writer

class Ui_ScrappingWindow(object):

    def scrapping(self):
        path = 'C:\Program Files\chromedriver_win32\chromedriver.exe'
        driver = webdriver.Chrome(path)

        next="/paintings?hitsPerPage=100"

        with open('ActiveFile.csv', "w", encoding='utf8', newline='') as f:
    
                thewriter =  writer(f)
                header = ['Name', 'Width', 'Height', 'Depth', 'Painter', 'Country','Price']
                thewriter.writerow(header)

                for i in range(1):

                        driver.get("https://www.saatchiart.com" + next)
                        content = driver.page_source
                        soup = BeautifulSoup(content)

                        page1 = soup.findAll('div',attrs={'class':'sc-15ws6ki-0 wZWfg'})
                        link = soup.find('a',attrs={'title':'Next'})
                        next=link['href']

                        for i in page1:

                                a = i.find('div',attrs={'data-type':'artwork-info'})
                                b = i.find('div',attrs={'data-type':'artist-info'})
                                c = i.find('div',attrs={'data-type':'prices'})
                                d = b.findAll('p')
                
                        name= a.p.a.text
                        size= a.find('span',attrs={'class':'sc-144xit5-0 juFwTn'})
                        size = size.text
                        data = size.split(" ")
                        width = data[0]
                        height = data[3]
                        depth = data[6]
                        painter = b.p.a.text
                        price = c.p.text
                        country = d[1].text
                        info = [name, width, height, depth, painter, country, price]
                        thewriter.writerow(info)    

    def startScrapping(self):
        self.scrapping()

    def setupUi(self, ScrappingWindow):
        ScrappingWindow.setObjectName("ScrappingWindow")
        ScrappingWindow.resize(1011, 509)
        ScrappingWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(ScrappingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 95))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label2 = QtWidgets.QLabel(self.frame_5)
        self.label2.setStyleSheet("background-image:url(:/resource/graphics/Auc_Store.jpg)")
        self.label2.setText("")
        self.label2.setPixmap(QtGui.QPixmap(":/resource/graphics/Auc_Store.jpg"))
        self.label2.setScaledContents(True)
        self.label2.setObjectName("label2")
        self.horizontalLayout_2.addWidget(self.label2)
        self.horizontalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label1 = QtWidgets.QLabel(self.frame_6)
        self.label1.setGeometry(QtCore.QRect(10, 13, 601, 41))
        self.label1.setStyleSheet("font: 20pt \"MS Reference Sans Serif\";\n"
"")
        self.label1.setObjectName("label1")
        self.label3 = QtWidgets.QLabel(self.frame_6)
        self.label3.setGeometry(QtCore.QRect(10, 60, 891, 21))
        self.label3.setStyleSheet("font: 10pt \"Times New Roman\";\n"
"COLOR:rgb(194, 129, 0);")
        self.label3.setObjectName("label3")
        self.horizontalLayout.addWidget(self.frame_6)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_3.setStyleSheet("background-color:rgb(225, 198, 129)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label1_2 = QtWidgets.QLabel(self.frame_3)
        self.label1_2.setStyleSheet("font: 18pt \"MS Reference Sans Serif\";\n"
"")
        self.label1_2.setObjectName("label1_2")
        self.horizontalLayout_3.addWidget(self.label1_2)
        self.btnStart = QtWidgets.QPushButton(self.frame_3, clicked = lambda: self.startScrapping() )
        self.btnStart.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.btnStart.setFont(font)
        self.btnStart.setStyleSheet("QPushButton:hover{\n"
"border: 2px solid rgb(217, 145, 48);\n"
"}")
        self.btnStart.setFlat(True)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout_3.addWidget(self.btnStart)
        self.btnPause = QtWidgets.QPushButton(self.frame_3)
        self.btnPause.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.btnPause.setFont(font)
        self.btnPause.setStyleSheet("QPushButton:hover{\n"
"border: 2px solid rgb(217, 145, 48);\n"
"}")
        self.btnPause.setFlat(True)
        self.btnPause.setObjectName("btnPause")
        self.horizontalLayout_3.addWidget(self.btnPause)
        self.btnResume = QtWidgets.QPushButton(self.frame_3)
        self.btnResume.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.btnResume.setFont(font)
        self.btnResume.setStyleSheet("QPushButton:hover{\n"
"border: 2px solid rgb(217, 145, 48);\n"
"}")
        self.btnResume.setFlat(True)
        self.btnResume.setObjectName("btnResume")
        self.horizontalLayout_3.addWidget(self.btnResume)
        self.btnStop = QtWidgets.QPushButton(self.frame_3)
        self.btnStop.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.btnStop.setFont(font)
        self.btnStop.setStyleSheet("QPushButton:hover{\n"
"border: 2px solid rgb(217, 145, 48);\n"
"}")
        self.btnStop.setFlat(True)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_3.addWidget(self.btnStop)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(50, 40, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.line1 = QtWidgets.QFrame(self.frame_7)
        self.line1.setGeometry(QtCore.QRect(30, 0, 31, 391))
        self.line1.setStyleSheet("background-color:rgb(193, 129, 0);")
        self.line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.label5 = QtWidgets.QLabel(self.frame_7)
        self.label5.setGeometry(QtCore.QRect(20, 10, 271, 151))
        self.label5.setStyleSheet("background-image:url(:/resource/graphics/I2.jpg)")
        self.label5.setText("")
        self.label5.setPixmap(QtGui.QPixmap(":/resource/graphics/I2.jpg"))
        self.label5.setScaledContents(True)
        self.label5.setObjectName("label5")
        self.label6 = QtWidgets.QLabel(self.frame_7)
        self.label6.setGeometry(QtCore.QRect(200, 190, 201, 171))
        self.label6.setStyleSheet("background-image:url(:/resource/graphics/I3.jpg)")
        self.label6.setText("")
        self.label6.setPixmap(QtGui.QPixmap(":/resource/graphics/I3.jpg"))
        self.label6.setScaledContents(True)
        self.label6.setObjectName("label6")
        self.label7 = QtWidgets.QLabel(self.frame_7)
        self.label7.setGeometry(QtCore.QRect(40, 260, 181, 111))
        self.label7.setStyleSheet("background-image:url(:/resource/graphics/I4.jpg)")
        self.label7.setText("")
        self.label7.setPixmap(QtGui.QPixmap(":/resource/graphics/I4.jpg"))
        self.label7.setScaledContents(True)
        self.label7.setObjectName("label7")
        self.label9 = QtWidgets.QLabel(self.frame_7)
        self.label9.setGeometry(QtCore.QRect(270, 30, 151, 201))
        self.label9.setStyleSheet("background-image:url(:/resource/graphics/I5.jpg)")
        self.label9.setText("")
        self.label9.setPixmap(QtGui.QPixmap(":/resource/graphics/I5.jpg"))
        self.label9.setScaledContents(True)
        self.label9.setObjectName("label9")
        self.label8 = QtWidgets.QLabel(self.frame_7)
        self.label8.setGeometry(QtCore.QRect(0, 140, 201, 121))
        self.label8.setStyleSheet("background-image:url(:/resource/graphics/I1.jpg)")
        self.label8.setText("")
        self.label8.setPixmap(QtGui.QPixmap(":/resource/graphics/I1.jpg"))
        self.label8.setScaledContents(True)
        self.label8.setObjectName("label8")
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setContentsMargins(75, -1, 75, -1)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblTotalEntities = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblTotalEntities.setFont(font)
        self.lblTotalEntities.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lblTotalEntities.setObjectName("lblTotalEntities")
        self.verticalLayout_5.addWidget(self.lblTotalEntities)
        self.txtTotalEntities = QtWidgets.QLineEdit(self.frame_10)
        self.txtTotalEntities.setReadOnly(True)
        self.txtTotalEntities.setObjectName("txtTotalEntities")
        self.verticalLayout_5.addWidget(self.txtTotalEntities)
        self.lblScrappedEntities = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblScrappedEntities.setFont(font)
        self.lblScrappedEntities.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lblScrappedEntities.setObjectName("lblScrappedEntities")
        self.verticalLayout_5.addWidget(self.lblScrappedEntities)
        self.txtScrappedEntities = QtWidgets.QLineEdit(self.frame_10)
        self.txtScrappedEntities.setReadOnly(True)
        self.txtScrappedEntities.setObjectName("txtScrappedEntities")
        self.verticalLayout_5.addWidget(self.txtScrappedEntities)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.ProgressBar = QtWidgets.QFrame(self.frame_11)
        self.ProgressBar.setGeometry(QtCore.QRect(130, 30, 100, 100))
        self.ProgressBar.setMinimumSize(QtCore.QSize(100, 100))
        self.ProgressBar.setMaximumSize(QtCore.QSize(100, 100))
        self.ProgressBar.setStyleSheet("border: 3px solid;\n"
"border-colo: rgb(0, 0, 0);\n"
"border-radius: 50")
        self.ProgressBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ProgressBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProgressBar.setObjectName("ProgressBar")
        self.verticalLayout_3.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnImportOriginal = QtWidgets.QPushButton(self.frame_12)
        self.btnImportOriginal.setMinimumSize(QtCore.QSize(0, 0))
        self.btnImportOriginal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.btnImportOriginal.setFont(font)
        self.btnImportOriginal.setStyleSheet("QPushButton:hover{\n"
"border: 2px solid rgb(225, 198,129);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(225, 198,129);\n"
"}")
        self.btnImportOriginal.setAutoDefault(True)
        self.btnImportOriginal.setDefault(False)
        self.btnImportOriginal.setFlat(False)
        self.btnImportOriginal.setObjectName("btnImportOriginal")
        self.verticalLayout_4.addWidget(self.btnImportOriginal)
        self.btnImportActive = QtWidgets.QPushButton(self.frame_12)
        self.btnImportActive.setMinimumSize(QtCore.QSize(0, 0))
        self.btnImportActive.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.btnImportActive.setFont(font)
        self.btnImportActive.setStyleSheet("QPushButton:hover{\n"
"border: 2px solid rgb(225, 198,129);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(225, 198,129);\n"
"}")
        self.btnImportActive.setAutoDefault(True)
        self.btnImportActive.setDefault(False)
        self.btnImportActive.setFlat(False)
        self.btnImportActive.setObjectName("btnImportActive")
        self.verticalLayout_4.addWidget(self.btnImportActive)
        self.verticalLayout_3.addWidget(self.frame_12)
        self.horizontalLayout_4.addWidget(self.frame_8)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        ScrappingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ScrappingWindow)
        QtCore.QMetaObject.connectSlotsByName(ScrappingWindow)

    def retranslateUi(self, ScrappingWindow):
        _translate = QtCore.QCoreApplication.translate
        ScrappingWindow.setWindowTitle(_translate("ScrappingWindow", "Scrapping Progress"))
        self.label1.setText(_translate("ScrappingWindow", "MYSTICAL CREATIONS"))
        self.label3.setText(_translate("ScrappingWindow", " WORLD\'S VERY FIRST ART EXHIBIT WITH THE FINEST PAINTINGS FROM AROUND THE GLOBE"))
        self.label1_2.setText(_translate("ScrappingWindow", "SCRAPPING"))
        self.btnStart.setText(_translate("ScrappingWindow", "START"))
        self.btnPause.setText(_translate("ScrappingWindow", "PAUSE"))
        self.btnResume.setText(_translate("ScrappingWindow", "RESUME"))
        self.btnStop.setText(_translate("ScrappingWindow", "STOP"))
        self.lblTotalEntities.setText(_translate("ScrappingWindow", "Total Number of Entities :"))
        self.lblScrappedEntities.setText(_translate("ScrappingWindow", "Number of Entities Scrapped :"))
        self.btnImportOriginal.setText(_translate("ScrappingWindow", "Import From Original Scrapped File"))
        self.btnImportActive.setText(_translate("ScrappingWindow", "Import From Active Scrapped File"))
import project_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ScrappingWindow = QtWidgets.QMainWindow()
    ui = Ui_ScrappingWindow()
    ui.setupUi(ScrappingWindow)
    ScrappingWindow.show()
    sys.exit(app.exec_())
